### ISSUE TITLE
NSG Flow Log Policy Dependencies

### ISSUE THREAD

**Issue by bduzik** [Azure/Community-Policy#116]
There appears to me unneeded dependencies in the resources section of the policy.  This causes issues if some services are removed from the policy.

https://github.com/Azure/Community-Policy/blob/master/Policies/Security/deployifnotexists-security-center-tier-by-service/azurepolicy.json#L197

**Comment by mrajess** [comment]
Let me take a look at that.

**Comment by kenieva** [comment]
There hasn't been any response on this thread so I will close the issue. If the problem persist or there are updates, please re-open.
