### ISSUE TITLE
not notEquals - differs from equals?

### ISSUE THREAD

**Issue by richeney** [Azure/Community-Policy#125]
Hi @mrajess 

Very quick question on the (rather nice) [deny-ports-nsg](https://github.com/Azure/Community-Policy/blob/master/Policies/Network/deny-ports-nsg/azurepolicy.json) policy which I'm adapting for JIT restrictions. 

Is there any reason why it uses:

```json
{
  "not": {
    "field": "Microsoft.Network/networkSecurityGroups/securityRules/sourceAddressPrefix",
    "notEquals": "*"
  }
}
```

on lines 12-17 rather than

```json
{
  "field": "Microsoft.Network/networkSecurityGroups/securityRules/sourceAddressPrefix",
  "equals": "*"
}
```

I think they're the same but is there a nuance I'm unaware of?

Thanks - Rich

**Comment by jesseloudon** [comment]
I'm interested in this question as well...it does appear that **{ not :{ notEquals: * }}** is the same as **{ equals: * }** 

I imagine the code was at some point originally

```
{
  "not": {
    "field": "Microsoft.Network/networkSecurityGroups/securityRules/sourceAddressPrefix",
    "equals": "*"
  }
}
```
Then was changed to current state as a quick fix.

**Comment by kenieva** [comment]
It should be the same.
