### ISSUE TITLE
Does the Azure APIM policy support operate the JSON file?

### ISSUE THREAD

**Issue by trongchata** [Azure/Community-Policy#153]
Does the APIM policy support operate the JSON file??

From Browser side:
HTTP Header_1 :  "Base 64 json file"

`
   {
       a : "a",
       b : "b"
   }
`

In the APIM policy : 
1. Read all the JSON from Header
2. Decode Base 64
3. Reformat the JSON file, and forward to backend service in another HTTP Header name

HTTP Header_2: "Base 64 json file"

`{
     c :
      {
           a : "a",
           b : "b"
      }
}`

Here is the example for this requirement.  Thanks

**Comment by kenieva** [comment]
Hi trongchata, this a repo for Azure Policy which is different from APIM policy. Thanks
