### ISSUE TITLE
An Azure Policy to deploy Diagnostic Settings for Azure Storage to Event Hub

### ISSUE THREAD

**Issue by raddaoui** [Azure/Community-Policy#189]
Currently Azure Storage account supports diagnostic settings to stream resource logs to Event Hub but unlike Log Analytics, there's no Azure Policy to enforce adding or Auditing storage accounts deployed without Diagnostic settings routing to Eventhub.

**Comment by mrajess** [comment]
https://github.com/Azure/Community-Policy/blob/master/Policies/Monitoring/deploy-diagnostic-setting-storage-account-event-hub/azurepolicy.json

Here you go. Just wrote and tested it. I'm going to close this out now.
