### ISSUE TITLE
Can't get the policy "Virtual Machine NIC must have NSG" to work

### ISSUE THREAD

**Issue by tamirboker** [Azure/Community-Policy#209]
Hello,

I tried to use the "Virtual Machine NIC must have NSG" policy to specifically block VMs NIC creation without NSG but when I deploy a new VM it passes validation without NSG.
My best guess is that the field "Microsoft.Network/networkInterfaces/virtualMachine.id", with which the policy makes sure the NIC belongs to a VM, is created after the initial validation.

Thanks

**Comment by azsec** [comment]
@tamirboker I'm afraid that you can achieve with `Deny` effect mode.  Based on your requirement, you could audit using `AuditIfNotExists`. Unfortunately as far as I know the `Deny` isn't working with `AuditIfNotExists`.

**Comment by SebastianClaesson** [comment]
Hi @tamirboker ,

You are correct, I would suggest writing a new policy that looks at all the Network Interfaces and always make sure a NSG is present, if not, deny the creation.

Are you still looking to create a policy for this? I can hopefully assist if so!

**Comment by techlake** [comment]
Cleaning up old issues (closing)
