### ISSUE TITLE
Error Cloning

### ISSUE THREAD

**Issue by cmaneiro** [Azure/Community-Policy#218]
error: unable to create file 
deploy-diagnostic-settings-to-azure-firewall/policies/Deploy_Diagnostic_Settings_for_Azure_Firewall_to_Log_Analytics_workspace_855bd88d-18bf-42c2-a519-9e7798bb7ee4/assign.Deploy_Diagnostic_Settings_for_Azure_Firewall_to_Log_Analytics_workspace_15f454a0c98e4178a3bcc7bf.json: Filename too long

**Comment by SebastianClaesson** [comment]
Hi @cmaneiro , Looks like this is a Windows file system limitation.
I'm taking a guess that this occured when you were cloning the repository.

You should be able to run the following command in your git client to allow all files to be downloaded.

```
git config --system core.longpaths true
```
