### ISSUE TITLE
Azure Policy JSON Schema?

### ISSUE THREAD

**Issue by JustinGrote** [Azure/Community-Policy#241]
I notice all these policies don't have a $schema associated with them. Is there a schema for just the JSON Policy (there's a schema for rules and schema for the arm template, but not for the policy that I can find). If not then how do you validate your azure policy JSON is correct?

**Comment by SebastianClaesson** [comment]
Hi @JustinGrote ,

There's no schema such as if you're doing a ARM template for subscription/tenant/resourcegroup deployment.
Instead the documented schema can be found here: [Azure Policy Fields](https://learn.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#fields)

There's a great Visual Studio Extension that can be used when writing these policies to assist with aliases and syntax.
[Azure Policy extension for Visual Studio Code](https://learn.microsoft.com/en-us/azure/governance/policy/how-to/extension-for-vscode)
