### ISSUE TITLE
Add a support for auditing Azure SQL databases which aren't enabled the active geo-replications

### ISSUE THREAD

**Issue by vienleidl** [Azure/Community-Policy#249]
There should be an Azure Policy for auditing the active geo-replications which are not enabled on Azure SQL databases.

**Comment by techlake** [comment]
Closed as completed.

**Comment by vienleidl** [comment]
> Hi @vienleidl ,
> 
> I've added a policy and made a pull request to the repository. It might not be 100% perfect but hopefully it will assist you in the progress of displaying these resources. I believe perhaps that a resource graph query on a dashboard might be more helpful for you thought :)
> 
> PR: #259

Thanks @SebastianClaesson! I found the replicationLinks property [here]( https://learn.microsoft.com/en-us/rest/api/sql/replication-links/list-by-database?view=rest-sql-2021-11-01&tabs=HTTP). However, I'm not sure if it works.
