### ISSUE TITLE
Creating Azure policies as bicep files.

### ISSUE THREAD

**Issue by SebastianClaesson** [Azure/Community-Policy#252]
All of the Azure policies so far generated are kept as ARM templates.
Is there an idea to also deliver these as bicep files that can be used as part of AzOps or other engines?

If so, I'd be happy to help to get that started.

**Comment by techlake** [comment]
Bicep is not on the roadmap.

I (Heinrich) recommend using https://aka.ms/epac for Policy deployment instead of ARM, BICEP, ... This is my personal opinion and may not reflect Microsoft's take.
