### ISSUE TITLE
DeployIfNotExists effect results in different compliance results versus Audit effect 

### ISSUE THREAD

**Issue by droessmj** [Azure/Community-Policy#273]
## Problem

I have a parameterized policy which works exactly as expected when in Audit mode. When flipped to DeployIfNotExists (DINE), the policy "works" in that it automatically remediates newly deployed resources correctly. It also correctly remediates existing resources when a remediation task is invoked. However, the Compliance state of the policy assignment itself shows 0 resources compliant once all in-scope resources have been remediated. I've read this [link](https://learn.microsoft.com/en-us/azure/governance/policy/concepts/effects#deployifnotexists) top to bottom multiple times, but nowhere do I see this behavior outlined. 

I'm trying to understand if this is a potential bug as we're doing an existenceCondition in line with other DINE examples. The differing behavior between Audit and DINE has us hyper-focused on the DINE portion. 

```
"parameters": {
      "effect": {
        "type": "String",
        "metadata": {
          "displayName": "Effect",
          "description": "Enable or disable the execution of the policy"
        },
        "allowedValues": [
          "DeployIfNotExists",
          "Disabled",
          "Audit"
        ],
        "defaultValue": "DeployIfNotExists"
      },
...
```

## Relevant Policy Snippet

```
 "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.KeyVault/vaults"
          },
          {
            "field": "Microsoft.KeyVault/vaults/enableRbacAuthorization",
            "equals": "false"
          },
          {
            "field": "Microsoft.Keyvault/vaults/accessPolicies[*].objectId",
            "notEquals": "[parameters('AadObjectId')]"
          }
        ]
      },
      "then": {
        "effect": "[parameters('effect')]",
        "details": {
          "type": "Microsoft.Keyvault/vaults/accessPolicies",
          "existenceCondition": {
            "allOf": [
              {
                "field": "Microsoft.Keyvault/vaults/accessPolicies[*].objectId",
                "notequals": "[parameters('AadObjectId')]"
              }
            ]
          },
...
```

This also exhibits the same behavior with an inverse and even simpler existenceCondition: 

```
        "existenceCondition": {
          "equals": "[parameters('wizAadObjectId')]",
          "field": "Microsoft.Keyvault/vaults/accessPolicies[*].objectId"
        },
```

**Comment by techlake** [comment]
Not a bug. DeployIfNotExists pairs with AuditIfNotExists. Audit doesn't read the existenceCondition in details in then.

Heinrich Gantenbein

From: Michael Droessler ***@***.***>
Sent: Wednesday, March 8, 2023 4:41 PM
To: Azure/Community-Policy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Azure/Community-Policy] DeployIfNotExists effect results in different compliance results versus Audit effect (Issue #273)

Problem

I have a parameterized policy which works exactly as expected when in Audit mode. When flipped to DeployIfNotExists (DINE), the policy "works" in that it automatically remediates newly deployed resources correctly. It also correctly remediates existing resources when a remediation task is invoked. However, the Compliance state of the policy assignment itself shows 0 resources compliant once all in-scope resources have been remediated. I've read this link<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fgovernance%2Fpolicy%2Fconcepts%2Feffects%23deployifnotexists&data=05%7C01%7C%7Ca14c6f9423474d5c9f6508db20263bd2%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638139121012820360%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8x%2BJIIqe2CmO6RPs%2Bp0%2BOK2PITeh7FelbXFWqTEq8vo%3D&reserved=0> top to bottom multiple times, but nowhere do I see this behavior outlined.

I'm trying to understand if this is a potential bug as we're doing an existenceCondition in line with other DINE examples. The differing behavior between Audit and DINE has us hyper-focused on the DINE portion.

"parameters": {

      "effect": {

        "type": "String",

        "metadata": {

          "displayName": "Effect",

          "description": "Enable or disable the execution of the policy"

        },

        "allowedValues": [

          "DeployIfNotExists",

          "Disabled",

          "Audit"

        ],

        "defaultValue": "DeployIfNotExists"

      },

...

Relevant Policy Snippet

 "policyRule": {

      "if": {

        "allOf": [

          {

            "field": "type",

            "equals": "Microsoft.KeyVault/vaults"

          },

          {

            "field": "Microsoft.KeyVault/vaults/enableRbacAuthorization",

            "equals": "false"

          },

          {

            "field": "Microsoft.Keyvault/vaults/accessPolicies[*].objectId",

            "notEquals": "[parameters('AadObjectId')]"

          }

        ]

      },

      "then": {

        "effect": "[parameters('effect')]",

        "details": {

          "type": "Microsoft.Keyvault/vaults/accessPolicies",

          "existenceCondition": {

            "allOf": [

              {

                "field": "Microsoft.Keyvault/vaults/accessPolicies[*].objectId",

                "notequals": "[parameters('AadObjectId')]"

              }

            ]

          },

...

-

**Comment by droessmj** [comment]
So to explicitly confirm, one should not expect resources to show as Compliant with a DINE or AINE policy -- only the non-compliant to be surfaced?

**Comment by techlake** [comment]
1. No, the allowedValues for parameter effect is wrong. They should be ["Disabled", "AuditIfNotExists", "DeployIfNotExists" ].
  * You cannot mix Audit and DeployIfNotExists
2. objectId should not be tested in if condition; use only in existenceCondition
3. logic between if (triggers action if true) and existenceCondition is reversed (triggers action if false)
4. ararys don't work that way, [*]. Please consult the docs. It is a difficult area

**Comment by droessmj** [comment]
Thanks for your feedback @techlake! Wish the overall policy authoring experience had a tighter feedback loop, but people like you help us all. Cheers.

**Comment by droessmj** [comment]
Closing the loop. There also was issues in referencing accessPolicies as the type within Key Vaults as per [here](https://github.com/Azure/azure-policy/issues/333). 

Final result, which appears to solve the issues:
```
    "if": {
        "allOf": [
            {
                "field": "type",
                "equals": "Microsoft.KeyVault/vaults"
            },
            {
                "field": "Microsoft.KeyVault/vaults/enableRbacAuthorization",
                "equals": "false"
            }
        ]
    },
    "then": {
        "effect": "[parameters('effect')]",
        "details": {
            "type": "Microsoft.KeyVault/vaults",
            "name": "[field('name')]",
            "existencecondition": {
                "count": {
                    "field": "Microsoft.Keyvault/vaults/accessPolicies[*]",
                    "where": {
                        "field": "Microsoft.Keyvault/vaults/accessPolicies[*].objectId",
                        "equals": "[parameters('aadObjectId')]"
                    }
                },
                "greater": 0
            },
...
``
