### ISSUE TITLE
NSG-Flow logs deployment policy is not working

### ISSUE THREAD

**Issue by mpalagir** [Azure/Community-Policy#275]
Hi @mrajess ,

Greetings!!

Kindly be informed that, below policy is unable to evaluate the non-compliant resource details when i pass target region as suggested but it is able to identify when i pass region as single location from the assignment parameters section. Please advise on this.

https://github.com/Azure/Community-Policy/blob/master/Policies/Network/deploy-nsg-flow-logs/azurepolicy.json

Thank you.

**Comment by techlake** [comment]
We are not fixing Policies contributed. Feel free to fix the Policy and submit a PR.
