### ISSUE TITLE
Contribution guide is contradictory

### ISSUE THREAD

**Issue by SebastianClaesson** [Azure/Community-Policy#281]
Under the section "Files, folders and naming conventions" there's a statement that a Azure policy needs to include 4 different files.

1. azurepolicy.json
2. azurepolicy.rules.json
3. azurepolicy.parameters.json
4. README.md

There's a description stating
- Include a README.md file that explains how the Azure Policy works, and how to assign it at scope.
- Guidelines on the README.md file below.

Same under "Pull requests"
PR must:
- Contain a single Policy (with 4 files)
- Requests for changes must be answered within 30 days
    - PR will be deleted after this time

However, there's also a section stating that the README.md is optional
https://github.com/Azure/Community-Policy/blob/master/CONTRIBUTING.md#readmemd-optional

Is the guideline that the README.md must be included or is it optional?

**Comment by techlake** [comment]
Optional. We are having a discusion around this topic and will refine the guidance soon.
