### ISSUE TITLE
Bulk-run Submit-PolicyDefinitionFile to fix existing Policies

### ISSUE THREAD

**Issue by techlake** [Azure/Community-Policy#287]

**Comment by SebastianClaesson** [comment]
What's the remaining steps of this? I'd be happy to help out!

**Comment by techlake** [comment]
Thank you for the offer. I had all the code already, just need to test it. I'm doing some additional things in restructuring and not defaulting some. I should have a solution this week.

I really like your coding style. While your contribution to this project came too late for inclusion, I'd like to suggest that you consider using my other favorite project and subsequently contribute. https://aka.ms/epac and https://github.com/Azure/enterprise-azure-policy-as-code.
