### ISSUE TITLE
Police NSG rules creation

### ISSUE THREAD

**Issue by beatrizpatricio7** [Azure/Community-Policy#3]
I was trying to create a police that automatically creates certain nsg rules, when an nsg is created. I have tried many ways, but with out any success. Is it possible to create this police?

Json code I tried:
{
  "properties": {
    "displayName": "Creat automatically deny-all-out Network Security Groups",
    "policyType": "Custom",
    "mode": "Indexed",
    "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.Network/networkSecurityGroups"
          }
        ]
      },
      "then": {
        "effect": "append",
        "details": [
          {
            "field": "Microsoft.Network/networkSecurityGroups/securityRules/direction",
            "value": "Outbound"
          },
          {
            "field": "Microsoft.Network/networkSecurityGroups/securityRules/sourcePortRanges",
            "value": "*"
          },
          
          {
            "field": "Microsoft.Network/networkSecurityGroups/securityRules/sourceApplicationSecurityGroups[*].name",
            "value": "Any"
          },
          {
            "field": "Microsoft.Network/networkSecurityGroups/securityRules/destinationPortRange",
            "value": "*"
          },
          {
            "field": "Microsoft.Network/networkSecurityGroups/securityRules/protocol",
            "value": "Any"
          },
          {
            "field": "Microsoft.Network/networkSecurityGroups/securityRules/access",
            "value": "Deny"
          },
          {
            "field": "Microsoft.Network/networkSecurityGroups/securityRules/priority",
            "value": "4096"
          }
        ]
      }
    }
  }
  }

**Comment by kenieva** [comment]
Hi @beatrizpatricio7 , 

Taking a quick glance at your policy, I have a feeling that the aliases used are not correct. I would recommend using the [VSCode extenstion](https://docs.microsoft.com/en-us/azure/governance/policy/how-to/extension-for-vscode) to check the aliases. 

Thanks, 

Kemley

**Comment by kenieva** [comment]
I made some modifications, can you try this policy to see if it works?

{
    "mode": "Indexed",
    "policyRule": {
        "if": {
            "field": "type",
            "equals": "Microsoft.Network/networkSecurityGroups"
        },
        "then": {
            "effect": "append",
            "details": [
                {
                    "field": "Microsoft.Network/networkSecurityGroups/securityRules[*].direction",
                    "value": "Outbound"
                },
                {
                    "field": "Microsoft.Network/networkSecurityGroups/securityRules[*].sourcePortRange",
                    "value": "*"
                },
                {
                    "field": "Microsoft.Network/networkSecurityGroups/securityRules[*].sourceApplicationSecurityGroups[*].id",
                    "value": "Any"
                },
                {
                    "field": "Microsoft.Network/networkSecurityGroups/securityRules[*].destinationPortRange",
                    "value": "*"
                },
                {
                    "field": "Microsoft.Network/networkSecurityGroups/securityRules[*].protocol",
                    "value": "Any"
                },
                {
                    "field": "Microsoft.Network/networkSecurityGroups/securityRules[*].access",
                    "value": "Deny"
                },
                {
                    "field": "Microsoft.Network/networkSecurityGroups/securityRules[*].priority",
                    "value": "4096"
                }
            ]
        }
    }
}

**Comment by beatrizpatricio7** [comment]
Hello Kenieva, 

I want to thank you for your help! I've tried, but still doesn't work. Do you think that is not possible or is something else?

I tried this code (I added all the parameters that were at the "export template" option, when we manually create a security rule)

{
  "mode": "Indexed",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.Network/networkSecurityGroups"
        }
      ]
    },
    "then": {
      "effect": "append",
      "details": [
        {
          "field": "Microsoft.Network/networkSecurityGroups/securityRules[*].name",
          "value": "denyallout"
        },
        {
          "field": "Microsoft.Network/networkSecurityGroups/securityRules[*].description",
          "value": "deny-all-out"
        },
        {
          "field": "Microsoft.Network/networkSecurityGroups/securityRules[*].protocol",
          "value": "*"
        },
        {
          "field": "Microsoft.Network/networkSecurityGroups/securityRules[*].sourcePortRange",
          "value": "*"
        },
        {
          "field": "Microsoft.Network/networkSecurityGroups/securityRules[*].destinationPortRange",
          "value": "*"
        },
        {
          "field": "Microsoft.Network/networkSecurityGroups/securityRules[*].sourceAddressPrefix",
          "value": "*"
        },
        {
          "field": "Microsoft.Network/networkSecurityGroups/securityRules[*].destinationAddressPrefix",
          "value": "*"
        },
        {
          "field": "Microsoft.Network/networkSecurityGroups/securityRules[*].access",
          "value": "deny"
        },
        {
          "field": "Microsoft.Network/networkSecurityGroups/securityRules[*].priority",
          "value": "4096"
        },
        {
          "field": "Microsoft.Network/networkSecurityGroups/securityRules[*].direction",
          "value": "Outbound"
        },
        {
          "field": "Microsoft.Network/networkSecurityGroups/securityRules[*].sourcePortRanges",
          "value": []
        },
        {
          "field": "Microsoft.Network/networkSecurityGroups/securityRules[*].destinationPortRanges",
          "value": []
        },
        {
          "field": "Microsoft.Network/networkSecurityGroups/securityRules[*].sourceAddressPrefixes",
          "value": []
        },
        {
          "field": "Microsoft.Network/networkSecurityGroups/securityRules[*].destinationAddressPrefixes",
          "value": []
        }
      ]
    }
  },
  "parameters": {}
}

**Comment by beatrizpatricio7** [comment]
Hello, 
I also tried this way. Doesn't show any error, but doesn't do anything too.

{
  "mode": "All",
  "policyRule": {
    "if": {
      "field": "type",
      "equals": "Microsoft.Network/networkSecurityGroups"
    },
    "then": {
      "effect": "deployIfNotExists",
      "details": {
        "type": "Microsoft.Network/networkSecurityGroups/securityRules",
        "name": "Deny-all-out",
        "roleDefinitionIds": [
          "/subscriptions/{subscriptionId}/providers/Microsoft.Authorization/roleDefinitions/{roleGUID}",
          "/providers/Microsoft.Authorization/roleDefinitions/{builtinroleGUID}"
        ],
        "deployment": {
          "properties": {
            "mode": "incremental",
            "template": {
              "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
              "contentVersion": "1.0.0.0",
              "resources": [
                {
                  "type": "Microsoft.Network/networkSecurityGroups",
                  "apiVersion": "2019-09-01",
                  "name": "Teste",
                  "location": "centralus",
                  "properties": {
                    "securityRules": [
                      {
                        "name": "Port11223344",
                        "properties": {
                          "protocol": "*",
                          "sourcePortRange": "*",
                          "destinationPortRange": "8080",
                          "sourceAddressPrefix": "*",
                          "destinationAddressPrefix": "*",
                          "access": "Allow",
                          "priority": 102,
                          "direction": "Inbound",
                          "sourcePortRanges": [],
                          "destinationPortRanges": [],
                          "sourceAddressPrefixes": [],
                          "destinationAddressPrefixes": []
                        }
                      }
                    ]
                  }
                }
              ]
            }
          }
        }
      }
    }
  },
  "parameters": {}
}

**Comment by kenieva** [comment]
Are you able to create a support ticket for us to look at this case more deeply? Our support engineers are training in create and debugging custom policies. Thanks!
