### ISSUE TITLE
VM App policy for Scaleset

### ISSUE THREAD

**Issue by jkroepke** [Azure/Community-Policy#377]
Hi!

I saw there is a policy for [VM Application and Windows Virtual machines](https://github.com/Azure/Community-Policy/tree/main/policyDefinitions/Compute/deploy-windows-vm-app).

Is there also a policy for VMSS? Thanks!

**Comment by aschabus** [comment]
We are not aware of any policy for VMSS, but we would happily accept any contribution for this.
Unfortunately, we cannot create new policies at request.
