### ISSUE TITLE
Links to Github broken on website

### ISSUE THREAD

**Issue by mundayn** [Azure/Community-Policy#388]
Hi,

Your folder structure has changed from 'Policies' to 'policyDefinitions'

This has broken the links under 'Name', for example:
https://www.azadvertizer.net/azpolicyadvertizer/monitoring_deploy-diagnostic-setting-for-activity-log-event-hub.html

![image](https://github.com/Azure/Community-Policy/assets/19361863/a075799c-6edc-42d4-838d-2d8eb81777e2)

![image](https://github.com/Azure/Community-Policy/assets/19361863/6d472e5c-5cfd-43f3-bb6b-3caa6354e1c5)

https://github.com/Azure/Community-Policy/tree/main/Policies/Monitoring/deploy-diagnostic-setting-for-activity-log-event-hub

to:

https://github.com/Azure/Community-Policy/tree/main/policyDefinitions/Monitoring/deploy-diagnostic-settings-for-activity-log-to-event-hub

**Comment by GitHubUser1339** [comment]
Looks like it has been fixed from AzAdvertizer side.
