### ISSUE TITLE
Undefined Parameter - configurationURL

### ISSUE THREAD

**Issue by zaidans** [Azure/Community-Policy#402]
Following error encountered while creating the custom policy - [deploy-dsc-extension-to-azure-vm-and-arc-connected-machines](https://github.com/Azure/Community-Policy/tree/main/policyDefinitions/Automation/deploy-dsc-extension-to-azure-vm-and-arc-connected-machines) 

Error/Bug
A function or parameter in policy '1e2e506d-89aa-46f1-8cf0-7660ae6dd7fa' could not be validated. If using template functions, try following the tips in: https://aka.ms/policy-avoiding-template-failures. The inner exception 'The policy '1e2e506d-89aa-46f1-8cf0-7660ae6dd7fa' has undefined parameter 'configurationUrl' which is used in the policy rule. Please either define it in policy definition or remove the reference in policy rule.'.

**Comment by aschabus** [comment]
@zaidans Thanks for making us aware of this bug.
Can you please use the azurepolicy.parameters.json file from the fix/#402-undefined-parameter branch and test if this works?
