### ISSUE TITLE
issue Address space must be pre-allocated to region policy

### ISSUE THREAD

**Issue by nachab** [Azure/Community-Policy#414]
The policy gives invalidparameters in split() function by array. It expects a string. The current value is:

"value": "[split(field('Microsoft.Network/virtualNetworks/virtualNetworkPeerings[*].remoteVirtualNetwork.id'), '/')[2]]",

the new one:

"value": "[split**(string**(field('Microsoft.Network/virtualNetworks/virtualNetworkPeerings[*].remoteVirtualNetwork.id')), '/')[2]]",

However, the change the policy is not working appropiately

**Comment by aschabus** [comment]
This is the policy we are talking about: https://github.com/Azure/Community-Policy/tree/main/policyDefinitions/Network/address-space-must-be-pre-allocated-for-region

**Comment by nachab** [comment]
Hi,

Yes this the policy

**Comment by Joshua-Donovan** [comment]
Hello @nachab, 

Thank you for pointing this issue out!

I was able to review the issue and I confirmed the problem of the split() function throwing an error on parameter type. 

Though when testing, your solution seemed to work without issue for me: 
"value": "[ split( string( field('Microsoft.Network/virtualNetworks/virtualNetworkPeerings[*].remoteVirtualNetwork.id') ), '/')[2] ]"

Added change to the example policy in the community repo: #421
