### ISSUE TITLE
Append AKS API IP Restrictions is not working

### ISSUE THREAD

**Issue by victordetoni** [Azure/Community-Policy#465]
![image](https://github.com/user-attachments/assets/f95b318e-9f55-4e33-af52-b4438fd8513d)
it seams Current Value and Target Value is incorret in the json file. Could you please help?

**Comment by DFRZ7** [comment]
Hi @victordetoni,

Thank you for bringing this up.

Upon reviewing your query, the reason for the non-compliance is that the current policy is only checking for the resource type:

```
"if":` {
  "field": "type",
  "equals": "Microsoft.ContainerService/managedClusters"
}
```

This condition alone will always result in non-compliance because it only verifies the existence of the resource type without assessing any additional conditions to determine compliance.

To address this, I’ve drafted and tested an updated policy:

```
{
  "mode": "Indexed",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.ContainerService/managedClusters"
        },
        {
          "field": "Microsoft.ContainerService/managedClusters/apiServerAccessProfile.authorizedIPRanges",
          "exists": "false"
        }
      ]
    },
    "then": {
      "effect": "[parameters('effect')]",
      "details": [
        {
          "field": "Microsoft.ContainerService/managedClusters/apiServerAccessProfile.authorizedIPRanges",
          "value": "[parameters('listOfAllowedIps')]"
        }
      ]
    }
  },
  "parameters": {
    "listOfAllowedIps": {
      "type": "Array",
      "metadata": {
        "displayName": "Allowed IPs",
        "description": "A list of IPs that are allowed to access the AKS API server."
      }
    },
    "effect": {
      "type": "String",
      "metadata": {
        "displayName": "Effect",
        "description": "Append, Deny, Audit, or Disable the execution of the Policy"
      },
      "allowedValues": ["Append", "Deny", "Audit", "Disabled"],
      "defaultValue": "Append"
    }
  }
}
```

With this updated policy, a resource will be marked compliant if the authorizedIPRanges property is present. If it's not, the resource will be marked non-compliant.

Please feel free to test this policy and let me know if there are any additional scenarios you'd like to consider before I proceed with submitting the PR mid-next week.

Thank you!

**Comment by victordetoni** [comment]
Hi David,

Thank you very much for the update. The update has made it "as compliant",
but it still allows for changing IP addresses manually and does not append
any new IP addresses to the list. I tried removing an IP address from the
AKS lists and the policy permited (expectation to not permited) and adding
a new IP address to the policy, but neither action worked. My expectation
is that the policy should prevent changes to the IP address list and append
new IP addresses when added. Ultimately, it should be compliant.

**Comment by victordetoni** [comment]
I just tried again disabling the API Policy Restrintion and it showed up as
"non-compliance", but it doesn't append any value to fix

**Comment by DFRZ7** [comment]
Hi @victordetoni,

Thank you for the additional details.

I've tested a new policy based on your observations:

**When creating the resource:**

If authorizedIPRanges is not added, the policy will allow creation and append the IPs for me.
If authorizedIPRanges is added but not all IPs are included, the policy will not allow creation.
If all IPs are correctly added, the policy will allow creation.

**After the resource is created:**

If the resource is created and we try to add IPs, the policy will not allow the change.
If we try to remove IPs, the policy will block the action.
If the same number of IPs is present but one is different, the policy will not allow the change.

Here's the draft for the updated policy:

```
{
  "mode": "Indexed",
  "policyRule": {
    "if": {
      "allOf": [
        {
          "field": "type",
          "equals": "Microsoft.ContainerService/managedClusters"
        },
        {
          "anyOf": [
            {
              "field": "Microsoft.ContainerService/managedClusters/apiServerAccessProfile.authorizedIPRanges",
              "exists": "false"
            },
            {
              "count": {
                "field": "Microsoft.ContainerService/managedClusters/apiServerAccessProfile.authorizedIPRanges[*]",
                "where": {
                  "field": "Microsoft.ContainerService/managedClusters/apiServerAccessProfile.authorizedIPRanges[*]",
                  "in": "[parameters('listOfAllowedIps')]"
                }
              },
              "less": "[length(parameters('listOfAllowedIps'))]"
            },
            {
              "count": {
                "field": "Microsoft.ContainerService/managedClusters/apiServerAccessProfile.authorizedIPRanges[*]"
              },
              "notEquals": "[length(parameters('listOfAllowedIps'))]"
            }
          ]
        }
      ]
    },
    "then": {
      "effect": "[parameters('effect')]",
      "details": [
        {
          "field": "Microsoft.ContainerService/managedClusters/apiServerAccessProfile.authorizedIPRanges",
          "value": "[parameters('listOfAllowedIps')]"
        }
      ]
    }
  },
  "parameters": {
    "listOfAllowedIps": {
      "type": "Array",
      "metadata": {
        "displayName": "Allowed IP's",
        "description": "A list of IP's that are allowed to access the AKS API server."
      }
    },
    "effect": {
      "type": "String",
      "metadata": {
        "displayName": "Effect",
        "description": "Append, Deny, Audit or Disable the execution of the Policy"
      },
      "allowedValues": ["Append", "Deny", "Audit", "Disabled"],
      "defaultValue": "Append"
    }
  }
}
```

Let me know your thoughts before I proceed with the PR.

**Comment by DFRZ7** [comment]
Hi @victordetoni if you could be so kind as to provide some additional details regarding the action you have in mind to perform.
At the end the conflict would be in a way another way to prevent changing to a value you do not allow. And conflict will be expected due to the nature of the append effect, in short, you could consider conflict as non compliant. Being this said, if you could provide us with more details regarding your last question. Thank you.

**Comment by victordetoni** [comment]
Hi David,

Thank you for your fast response and support. I meant that I expected the
policy to automatically fill in the authorizedIPRanges when it detected
that they were incorrect.

Based on your explanation, this version is working very well.

**Comment by DFRZ7** [comment]
@victordetoni I understand, unfortunatelly based on tests you would need to perform the changes manually, unless you are creating or updating with the correct settings. If anything else, do let us know of course.

**Comment by victordetoni** [comment]
That’s perfect! Thank you for your full support

Em qua., 11 de set. de 2024 às 13:47, David Florez Ramirez <
***@***.***> escreveu:
